#ifndef XTT_UTIL_ERRORS_H
#define XTT_UTIL_ERRORS_H
#pragma once

#define SUCCESS 0
#define SAVE_TO_FILE_ERROR -1
#define READ_FROM_FILE_ERROR -2
#define KEY_CREATION_ERROR -3
#define CERT_CREATION_ERROR -4
#define ASN1_CREATION_ERROR -5
#define EXPIRY_PASSED -6
#define PARSE_CERT_ERROR -7
#define SERVER_ERROR -8
#define CLIENT_ERROR -9
#define TPM_ERROR -10
#define CRYPTO_HASH_ERROR -11
#define VOID_SUCCESS -12

#endif
